# fly.toml app configuration file generated for samushaoge on 2026-02-10T07:40:06Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'samushaoge'
primary_region = 'fra'

[build]

# Run DB migrations before switching to the new release. If this fails, deploy is aborted.
[deploy]
  release_command = "npx knex migrate:latest"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = "off"   # Stop killing the process
  auto_start_machines = true
  min_machines_running = 1    # Keep at least one instance alive at all times
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
