# fly.toml app configuration file generated for samushaoge on 2026-02-10T07:40:06Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'samushaoge'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = "off"   # Stop killing the process
  auto_start_machines = true
  min_machines_running = 1    # Keep at least one instance alive at all times
  processes = ['app']

[[vm]]
  cpu_kind = "performance"
  cpus = 1   # performance-1x
  memory_mb = 2048
